---
  - hosts: localhost
    connection: local
    tasks:
      - name: Set some kernel parameters
        lineinfile:
          dest: "~/cluster/hosts"
          line: "{{ item.line }}"
        with_items:
          - { line: '[master]' }
          - { line: "{% for host in groups.minicloud %}{{ hostvars[host].ansible_ssh_host }}\n{% endfor %}" }
          - { line: '[worker]' }
          - { line: "{% for host in groups.minicloud %}{{ hostvars[host].ansible_ssh_host }}\n{% endfor %}" }
          - { line: '[proxy]' }
          - { line: "{% for host in groups.minicloud %}{{ hostvars[host].ansible_ssh_host }}\n{% endfor %}" }
